### ISSUE TITLE
Need drag and drop functionality

### ISSUE THREAD

**Issue by sudhishvnair** [FlowingCode/OrgChartAddon#1]
Hi,
    my company is using this add on on a project to show the organizational chart. we need to support the drag and drop functionality. any chance to get the functionality in ?

**Comment by mlopezFC** [comment]
Hi,
Yes, our idea is to improve the component if there are active users. One question, do you want to use drag and drop just for visualization purposes, or do you want it to be fully "editable" and to be able to persist those changes in the backing model?
Regards.

**Comment by sudhishvnair** [comment]
Hi,
  We need both for visualization as well as to persist the data. Our requirement is basically if you drag a resource from one organizational unit to another, the resource should be reassigned to the new organization.

Regards.

**Comment by mlopezFC** [comment]
Great, thanks for the feedback. We are currently analyzing the implementation strategy. I will let you know here about the development status.

**Comment by paodb** [comment]
Hi @sudhishvnair, we just released version 2.0.1 of this add-on implementing this feature. Go over to Vaadin directory to check it out. We'll appreciate your feedback. Thanks!
