### ISSUE TITLE
how to develop an addon for vaadin?

### ISSUE THREAD

**Issue by LancCJ** [FlowingCode/OrgChartAddon#11]
HI，This AddOn is helpful。I want to konw how to develop an addon for vaadin,because i need to develop one for my project,but i don not konw where i can learn from,can you give me a website for me?thks

**Comment by mlopezFC** [comment]
Hi! ... first place to look for Vaadin related documentation [would be here](https://vaadin.com/docs/index.html). But if you want to develop an extension based on (as an example) a Javascript library, then [this article might be worth reading](https://www.flowingcode.com/en/creating-a-vaadin-flow-server-side-api-for-a-javascript-component/).

Closing this given that this is not an issue, if you have trouble using our addon please create one.

Regards!
