### ISSUE TITLE
nodeTemplate with the Addon..?

### ISSUE THREAD

**Issue by vimalkumar010** [FlowingCode/OrgChartAddon#12]
Is it possible to put nodeTemplate using this Addon...?

**Comment by javier-godoy** [comment]
Support for node template was added in version 2.0.3. There is an example in the [demo](https://github.com/FlowingCode/OrgChartAddon/blob/b1b36ebc050cfecbbcc124f70314349bc6fc40b4/orgchart-addon-demo/src/main/java/com/flowingcode/vaadin/addons/orgchart/demo/DemoUI.java#L55).
