### ISSUE TITLE
Build error in Windows (jsPDF/FileSaver dependencies)

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/OrgChartAddon#16]
Orgchart depends on a broken version of jspdf (see https://github.com/MrRio/jsPDF/issues/2208), which causes a production build to fail in Windows with the following message:

```
[INFO] Running `npm install` ...
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by javier-godoy** [comment]
Fixed

**Comment by begench993** [comment]
>> npm install jspdf --save
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
I got same

**Comment by javier-godoy** [comment]
Can you try with version 4.0.2 of the addon?
