### ISSUE TITLE
Hashcode Integers as Ids 

### ISSUE THREAD

**Issue by vexa** [FlowingCode/OrgChartAddon#42]
Hi, 
When you use large Integers as Id the client to Server transport breaks. 

I got this problem because i use Java hashcodes as ids for the node. When you click the Node on the Java backend you got an string link 1.34342e6 ... after that you try to parse the Integer and result in an  error. 

To fix this problem you can do the following in fc-orgchat.js
`        	'createNode': function($node, data) {
    	        $node.on('click', function() {
    	        	currOrgChart.$server.onClick(data.id.toString());  // here is the fix 
    	        });
    	        `

**Comment by paodb** [comment]
@vexa this is a great catch! Thanks for the tip on how to fix it!
