### ISSUE TITLE
setChartExpandCollapse doesn't seem to work properly

### ISSUE THREAD

**Issue by Charlie28000** [FlowingCode/OrgChartAddon#50]
Despite using setChartExpandCollapse(true) the HTML looks like this: 
`<div class="orgchart noncollapsable" ...>`

The issue can also be observed in the Demo (Drag and Drop Tab): https://addonsv14.flowingcode.com/orgchart 

**EDIT:** 
Using setChartDirection(ChartDirectionEnum.TOP_TO_BOTTOM.getAbreviation()) allows collapsing most nodes, except for one last node below the root node. Also the collapse / expand arrows don't show up at all, so the end user wouldn't know, that the nodes are collapsable.

**Comment by paodb** [comment]
Hi @Charlie28000 good catch on the collapsable issue. I was just able to reproduce it and I'll work on the fix.

Regarding "_Using setChartDirection(ChartDirectionEnum.TOP_TO_BOTTOM.getAbreviation()) allows collapsing most nodes, except for one last node below the root node_." Please note that the collapsable functionality comes from the original library, our add-on only gives you a way to set it from Java (see [this](https://codepen.io/dabeng/pen/VWgdzp) example from the library). If you think this is an issue can you please create a separate ticket with an example/image/gif showing that behavior? Thanks.

**Comment by Charlie28000** [comment]
Hi @paodb, 
thank you very much! Will the Vaadin Component (https://vaadin.com/directory/component/orgchart-add-on) also be updated? 
Okay, I'll investigate a little bit further and create a ticket regarding the other issue, providing screenshots.

**Comment by paodb** [comment]
Hi @Charlie28000, we just did a new release of the component that contains this fix, version 4.2.1. Thanks again for the feedback.
