### ISSUE TITLE
Cannot see arrow indicators on nodes

### ISSUE THREAD

**Issue by dcmlx** [FlowingCode/OrgChartAddon#53]
Hello

The arrow indicators for collapsing and expanding the org tree are not appearing for me. Here is an an example of the code.

```java
 OrgChartItem item1 = new OrgChartItem(1, "Root item", "Root Level");
        OrgChartItem item2 = new OrgChartItem(2, "Item 2", "Level 1");
        OrgChartItem item3 = new OrgChartItem(3, "Item 3", "Level 1");
        item1.setChildren(Arrays.asList(item2, item3));

        OrgChart orgChart = new OrgChart(item1);
        orgChart.setChartTitle("A Title");
        orgChart.setChartNodeContent("title");
        orgChart.setChartExportButton(true);
        orgChart.setChartDraggable(true);
        orgChart.setChartExpandCollapse(true);

        add(orgChart);
```

Any idea why this is not working? I am using vaadin 21 with version 4.2.1 or the org chart.

thanks!

![image](https://user-images.githubusercontent.com/78946/140167632-e00c419a-b96d-440d-a5b4-299fb613a7ca.png)

**Comment by Charlie28000** [comment]
Hi @dcmlx, 

I was facing the same issue. Turns out Font Awesome (which was used for the arrows) wasn't working properly in my project setup. Hope this helps!

**Comment by paodb** [comment]
Hello @dcmlx, sorry for the delay on this. @Charlie28000 is correct, this has to do with the fact that is using FontAwesome to draw the arrows but the dependency is not included in the addon itself. If you take a look at the [test module](https://github.com/FlowingCode/OrgChartAddon/tree/master/src/test) in the repository, you can see that we are adding a [css for font-awesome](https://github.com/FlowingCode/OrgChartAddon/tree/master/src/test/resources/META-INF/resources/frontend/styles/orgchart) that is then imported in [OrgchartDemoView](https://github.com/FlowingCode/OrgChartAddon/blob/a8f9ee6e36edb36263e7944d95bec355864033a7/src/test/java/com/flowingcode/vaadin/addons/orgchart/OrgchartDemoView.java#L31). Also, you need to add the dependency for FontAwesome in your pom.xml (if you're not already using it).

I did a little Vaadin 21 test project with your example and it works okay. What I did:
- Add the FontAwesome dependency to the pom.xml:
```
<dependency>
      <groupId>org.webjars</groupId>
      <artifactId>font-awesome</artifactId>
      <version>4.7.0</version>
  </dependency>
``` 
- Copy font-awesome.css from the test module and add it to the project in \src\main\resources\META-INF\resources\frontend\styles\orgchart\font-awesome.css
- Then add the @CssImport annotation like: 

```
@CssImport("./styles/orgchart/font-awesome.css")
public class MainView extends VerticalLayout {

    public MainView() {
        OrgChartItem item1 = new OrgChartItem(1, "Root item", "Root Level");
        OrgChartItem item2 = new OrgChartItem(2, "Item 2", "Level 1");
        OrgChartItem item3 = new OrgChartItem(3, "Item 3", "Level 1");
        OrgChartItem item4 = new OrgChartItem(4, "Item 4", "Level 2");
        OrgChartItem item5 = new OrgChartItem(5, "Item 5", "Level 2");
        item1.setChildren(Arrays.asList(item2, item3));
        item3.setChildren(Arrays.asList(item4, item5));

        OrgChart orgChart = new OrgChart(item1);
        orgChart.setChartTitle("A Title");
        orgChart.setChartNodeContent("title");
        orgChart.setChartExportButton(true);
        orgChart.setChartDraggable(true);
        orgChart.setChartExpandCollapse(true);

        add(orgChart);
    }
}
```
Hope this helps.
