### ISSUE TITLE
V14 - Exported file is missing format/styling

### ISSUE THREAD

**Issue by paodb** [FlowingCode/OrgChartAddon#65]
Go to https://addonsv14.flowingcode.com/orgchart/drag-and-drop and click "Export" button. Resulting file shows barely visible data and no styling.

![image](https://user-images.githubusercontent.com/30666649/235237891-3369cb77-d15e-4d1d-8aa0-2e956fdb1c44.png)

**Comment by paodb** [comment]
The issue happens randomly. When the export breaks it can also be observed that routing for the other tabs in the demo is broken too. An extra value is added to the path, for example: addonsv14.flowingcode.com/orgchart/orgchart/image-title and in that case, the demo is broken, as resources are not loaded

![image](https://github.com/FlowingCode/OrgChartAddon/assets/30666649/d03c2f09-346d-4919-8da1-a6bde24237bf)

This seems to be related to https://github.com/FlowingCode/OrgChartAddon/issues/72

**Comment by paodb** [comment]
I can't reproduce the missing format/styling thing with the new version (5.0.0) but the issue with the malformed urls after export is still there.

**Comment by javier-godoy** [comment]
"Exported file is missing format/styling" seems to be fixed in v5.0.0.
The URL issue was reported in #72
