### ISSUE TITLE
Add-on is not rendered in V24.1

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/OrgChartAddon#67]
Vaadin: 24.1.0
Add-on: 4.2.3-SNAPSHOT

Add-on does not load in demo site. The following error is logged in the browser console.
```
FlowClient-d5d5e377.js:3 ReferenceError: require is not defined
    at fc-orgchart-322b91d3.js:15:15177
    at fc-orgchart-322b91d3.js:15:15237
    at fc-orgchart-322b91d3.js:1:25
    at fc-orgchart-322b91d3.js:24:130
```

**Comment by paodb** [comment]
I tried running the demo locally in dev-mode it works okay, in production mode, it breaks as reported. Checking browser error logs, it seems the issue might be within the library https://github.com/FlowingCode/OrgChartAddon/blob/bcc3b1626d52eb0bc09d7aecae499dc560f09127/src/main/resources/META-INF/frontend/orgchart/dist/js/jquery.orgchart.js#L17
Will investigate more.
